### ISSUE TITLE
String

### ISSUE THREAD

**Issue by D-Antonelli** [D-Antonelli/geeks_for_geeks_dsa_solutions#12]
**TODO**

- [ ] [Read this article ](https://www.geeksforgeeks.org/introduction-to-strings-data-structure-and-algorithm-tutorials/)
- [ ] [Read this article](https://www.geeksforgeeks.org/what-is-string/?ref=roadmap)
- [ ] https://www.techinterviewhandbook.org/algorithms/string/
- [ ] Do 3 questions about Strings
